image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

generate_version_doc:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -qq update && apt-get install -y --no-install-recommends apt-utils
    - apt install -qq -y python3
                         python3-pip
                         ssh
                         git
                         numactl
                         dos2unix
                         rsync
                         tzdata
    - dpkg-reconfigure --frontend noninteractive tzdata
    - apt install -qq -y texlive-latex-extra latexmk
    - apt -y clean
    - python3 -m pip install sphinx
                             matplotlib
                             ipython
                             sphinxcontrib-fulltoc
                             numpydoc
    - 'which ssh-agent || ( apt install -qq -y openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp $CASCOPY ~/
  script:
    - cd package
    - git remote remove gitlab || echo "Not exist"
    - git remote add gitlab $GITLAB_LINK || git remote show gitlab
    - git fetch gitlab
    - git checkout $BRANCH
    - git pull gitlab $BRANCH
    - python3 setup.py install
    - cd ..
    - ./generate_latest.sh
    - ssh $FINALHOST "rm -rf $FINALDEST/*"
    - scp -r gh-pages/sasoptpy $FINALHOST:$FINALDEST/
  artifacts:
    paths:
      - gh-pages/
    expire_in: 24 hours
  when: manual

