image: ubuntu:latest

before_script:
  - apt -y -qq update && apt -y -qq upgrade
  - apt install python3
    		python3-pip
		ssh
		git
		numactl
		texlive-latex-extra
  - apt clean
  - python3 -m pip install sphinx
			   matplotlib
			   ipython
			   sphinxcontrib-fulltoc
			   numpydoc

stages:
  - setup
  - config
#  - build
#  - commit

setup:
  stage: setup
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp $CASCOPY ~/

config:
  stage: config
  script:
    - cd package
    - git remote add gitlab $GITLAB_LINK
    - git fetch gitlab
    - git merge gitlab/$BRANCH

