image: sertalpbilal/sphinx_dev:1.0.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

generate_version_doc:
  before_script:
    - 'which ssh-agent || ( apt install -qq -y openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp $CASCOPY ~/
  script:
    - git submodule update --init --recursive
    - cd package
    - git config --global user.email "root@docker"
    - git config --global user.name "Docker"
    - git remote remove gitlab || echo "Not exist"
    - git remote add gitlab $GITLAB_LINK || git remote show gitlab
    - git fetch gitlab
    - git fetch --tags
    - git checkout --track gitlab/$BRANCH || git checkout $BRANCH
    - git pull gitlab $BRANCH
    - git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(refname:short) - %(objectname:short) - %(contents:subject) - %(authorname) (%(committerdate:relative))'
    - git rev-parse HEAD
    - python3 setup.py install --force
    - cd ..
    - ./generate_latest.sh
    - cd gh-pages/sasoptpy
    - git remote remove gitlab || echo "Not exist"
    - git remote add gitlab $GITLAB_LINK || git remote show gitlab
    - git fetch gitlab
    - git add -A
    - git checkout -q -b gh-candidate-$(date '+%Y%m%d-%H%M%S')
    - git commit -q -m "Documentation page update"
    - git push gitlab -u HEAD
  artifacts:
    paths:
      - gh-pages/
    expire_in: 24 hours
  when: manual
